### ISSUE TITLE
Traceback (most recent call last):   File "run.py", line 46, in <module>     train_loader = dm.get_dataset(data_type='train')   File "/user-data/lm_ner_span-main/DataManager.py", line 34, in get_dataset     dataloader = self.data_process(file)   File "/user-data/lm_ner_span-main/DataManager.py", line 68, in data_process     sampler = RandomSampler(tokenized_datasets) if not torch.cuda.device_count() > 1 else DistributedSampler(tokenized_datasets)   File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 103, in __init__     raise ValueError("num_samples should be a positive integer " ValueError: num_samples should be a positive integer value, but got num_samples=0 请问这个报错怎么解决啊   好像是dataloader出错了  但是按照网上的解决办法将参数shuffle设置为FALSE还是没办法解决  请问大佬有什么解决办法吗

### ISSUE THREAD

**Issue by 20214021016** [wzzzd/lm_ner_span#3]

**Comment by wzzzd** [comment]
检查一下dataloader是否成功读取到数据？

**Comment by wzzzd** [comment]
报错原因是sample为0，检查一下dataloader是否成功读取到数据？

**Comment by CRonaldo1997** [comment]
指定sep为'\t'即可
